### PR TITLE
Mpp fix

### PR DESCRIPTION
**Pull request by zankner**

### CODE REVIEW

**Comment by iNeil77** [comment]
Just a heads up, could you guys merge this in please. Took me a while to figure out the mask token dimensions problem. The MPP example given in the README works out of pure luck due to the specific numbers chosen.

**Comment by LY080835** [comment]
@zankner I wanted to know about reference paper for: masked patch prediction. Can you tell me? Think you very much.

**Comment by iNeil77** [comment]
> @zankner I wanted to know about reference paper for: masked patch prediction. Can you tell me? Think you very much.

I believe this is the one:
https://openaccess.thecvf.com/content/CVPR2022/html/He_Masked_Autoencoders_Are_Scalable_Vision_Learners_CVPR_2022_paper

**Comment by LY080835** [comment]
ok, thank you

**Pull request merged**
