### PR TITLE
begin work on NaViT (wip)

### PR DESCRIPTION
**Pull request by lucidrains**
a couple open source folks i talk to privately were excited about this paper

so i'll just get it built today and tomorrow

### CODE REVIEW

**Comment by b5y** [comment]
Hello @lucidrains !

Thank you a lot for your work on NaViT model. It's very impressive and useful.

Could you please provide some dummy example as you gave for [ViT](https://github.com/lucidrains/vit-pytorch/blob/main/examples/cats_and_dogs.ipynb) model?

I have tried to reproduce on the same example as for ViT, but caught an error:

```bash
---------------------------------------------------------------------------
AssertionError                            Traceback (most recent call last)
Cell In[55], line 9
      6 data = data.to(device)
      7 label = label.to(device)
----> 9 output = model(data)
     10 loss = criterion(output, label)
     12 optimizer.zero_grad()

File [~/anaconda3/envs/uni/lib/python3.10/site-packages/torch/nn/modules/module.py:1518](http://localhost:8888/lab/tree/Aalto/vit-pytorch/examples/anaconda3/envs/uni/lib/python3.10/site-packages/torch/nn/modules/module.py#line=1517), in Module._wrapped_call_impl(self, *args, **kwargs)
   1516     return self._compiled_call_impl(*args, **kwargs)  # type: ignore[misc]
   1517 else:
-> 1518     return self._call_impl(*args, **kwargs)

File [~/anaconda3/envs/uni/lib/python3.10/site-packages/torch/nn/modules/module.py:1527](http://localhost:8888/lab/tree/Aalto/vit-pytorch/examples/anaconda3/envs/uni/lib/python3.10/site-packages/torch/nn/modules/module.py#line=1526), in Module._call_impl(self, *args, **kwargs)
   1522 # If we don't have any hooks, we want to skip the rest of the logic in
   1523 # this function, and just call forward.
   1524 if not (self._backward_hooks or self._backward_pre_hooks or self._forward_hooks or self._forward_pre_hooks
   1525         or _global_backward_pre_hooks or _global_backward_hooks
   1526         or _global_forward_hooks or _global_forward_pre_hooks):
-> 1527     return forward_call(*args, **kwargs)
   1529 try:
   1530     result = None

File [~/anaconda3/envs/uni/lib/python3.10/site-packages/vit_pytorch/na_vit.py:284](http://localhost:8888/lab/tree/Aalto/vit-pytorch/examples/anaconda3/envs/uni/lib/python3.10/site-packages/vit_pytorch/na_vit.py#line=283), in NaViT.forward(self, batched_images, group_images, group_max_seq_len)
    279 image_ids = torch.empty((0,), device = device, dtype = torch.long)
    281 for image_id, image in enumerate(images):
    282     # print("Image.ndim: ", image.ndim)
    283     # print("Image.shape[0]: ", image.shape[0])
--> 284     assert image.ndim ==3 and image.shape[0] == c
    285     image_dims = image.shape[-2:]
    286     assert all([divisible_by(dim, p) for dim in image_dims]), f'height and width {image_dims} of images must be divisible by patch size {p}'

AssertionError:
```

The model I was trying to use is defined like this:

```python
model = NaViT(
    image_size=224,
    patch_size=32,
    num_classes=2,
    channels=3,
    dim = 1024,
    depth = 6,
    heads = 16,
    mlp_dim = 2048,
    dropout = 0.1,
    emb_dropout = 0.1,
    token_dropout_prob = 0.1  # token dropout of 10% (keep 90% of tokens)
)
```

**Comment by dempsey-ryan** [comment]
@b5y Assuming your input is a list of tensor images, each image in your input list must be of shape (c, x, y), where c is number of channels (in your case, 3). The assert statement is failing because either a) the image has more than 3 dimensions (e.g. (c, x, y, z)), or the channel dimension is wrong, e.g. (c+1, x, y) or (x, y, c).

Make sure the channel is the first dimension - Matplotlib usually has the channel in a different place from Pytorch, so you might need to transpose()!

See the [readme](https://github.com/lucidrains/vit-pytorch?tab=readme-ov-file#navit) for an example

**Comment by b5y** [comment]
The output of

```python
train_loader.dataset[0][0].shape
```
is

```bash
torch.Size([3, 224, 224])
```

which is pretty much the same what is in example. But If I print `data.shape` during training epoch, the shape is

```bash
torch.Size([64, 3, 224, 224])
```

Is there something I am missing here?

**Comment by dempsey-ryan** [comment]
The first shape is the shape of a single sample. The second shape is a batch of images. In order to leverage the parallelism of neural networks, we input multiple samples at once in a single tensor, called a batch. The novelty of NaViT is that it can automatically pack varying sizes of images into a single batch without user intervention (it does so by operating on sequences of image patches, which are then packed to form a single sequence).

I highly suggest you read up on basic neural networks and torch to understand the fundamentals (e.g. batch size, adam optimization, dataset vs. dataloader, etc.) before posting questions on more advanced architectures like ViTs which are built on the fundamentals. DeepLearning.AI is a great fundamental course that is very popular for example

**Comment by b5y** [comment]
Hello @lucidrains !

Another question came with NaViT usage. How do you use NaViT for multi-GPU training?
In some of my previous (where `trainer` is not defined via `transformers`) computer vision models I followed this approach:

```python
if torch.cuda.device_count() > 1:
    print("Let's use", torch.cuda.device_count(), "GPUs!")
    model = nn.DataParallel(model)

model.to(device)
```

which is Data Parallel (DP). I know there are some other approaches, but since this worked well, I followed it. And then I run the script on terminal like this:

```bash
MAX_JOBS=12 OMP_NUM_THREADS=24 torchrun --nproc_per_node 2 train_navit.py
```

Any suggestions or ideas?

**Comment by b5y** [comment]
UPDATE: Passing `num_samples` in `RandomSampler` inside `DataLoader` with the same amount as `train_batch_size` did the trick. No need to use Data Parallel or anything else.

**Pull request merged**
